/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "GPIO.h"
#include "Console.h"

int main(void)
{
	float freq = 0;
	MCU_Clock_Init(Use_External_Crystal);
	Console_Init(115200);


    /* Loop forever */
	for(;;)
	{
		freq = 1.0/((1.0/1000000.0)*(float)(TIM1->CCR1));
		printConsole("Frequency = %f \r\n", freq);
	}
}
