/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "CAN.h"

int main(void)
{
    MCU_Clock_Init();
    Delay_Config();
    CAN_Init(CAN_BAUDRATE_1000_KBPS);
    GPIO_Pin_Setup(GPIOC, 13, GEN_PUSH_PULL_OUTPUT);

	for(;;)
	{
		GPIOC -> BSRR |= GPIO_BSRR_BR13;

		GPIOC -> BSRR |= GPIO_BSRR_BS13;
		Delay_ms(100);
	}
}
